name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Install InvokeBuild -Force
          run: Install-Module InvokeBuild
          shell: pwsh
        - name: Build
          run: Invoke-Build
          shell: pwsh